GET http://localhost:8080/api/movies/
###
POST http://localhost:8080/api/movies/add/
Content-Type: application/json

{
"title": "Avengers: Endgame",
"imdbId": "tt4154796",
"thumbsUp": "1",
"thumbsDown": "3"
}
###
PATCH http://localhost:8080/api/movies/0/
Content-Type: application/json

{
"thumbsUp": "3",
"thumbsDown": "6"
}