GET http://localhost:8080/api/movies/
###
POST http://localhost:8080/api/movies/add/
Content-Type: application/json

{
"title": "Avengers: Endgame",
"imdbId": "tt4154796",
"thumbsUp": "1",
"thumbsDown": "3"
}
###
POST http://localhost:8080/api/movies/1/thumbsUp